# Generated by Django 6.0.4 on 2026-04-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('age', models.IntegerField()),
                ('activity_level', models.FloatField(choices=[(1.2, 'Sedentary (1.2)'), (1.4, 'Lightly active (1.4)'), (1.6, 'Moderately active (1.6)')])),
                ('goal', models.CharField(choices=[('Lose', 'Lose Weight'), ('Maintain', 'Maintain Weight'), ('Gain', 'Gain Weight')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
