# Generated by Django 6.0.4 on 2026-04-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
