# Generated by Django 6.0.4 on 2026-04-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_healthcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheck',
            name='activity_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='goal',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
