# Generated by Django 6.0.4 on 2026-04-17 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='default_recipe.png', upload_to='recipes/')),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('cooking_time', models.IntegerField(default=15, help_text='Cooking time in minutes')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('Breakfast', 'فطور'), ('Lunch', 'غداء'), ('Dinner', 'عشاء'), ('Snack', 'سناك')], max_length=50)),
                ('diet_type', models.CharField(choices=[('Regular', 'عادي'), ('Keto', 'كيتو'), ('Vegan', 'نباتي'), ('Vegetarian', 'نباتي (ألبان/بيض)'), ('GlutenFree', 'خالي من الجلوتين')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='nutrition.chefprofile')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
