# Generated by Django 6.0.4 on 2026-04-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0011_remove_userprofile_user_type_recipe_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='chef_tip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('Easy', 'سهل'), ('Medium', 'متوسط'), ('Hard', 'محترف')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
