# Generated by Django 6.0.4 on 2026-04-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0012_recipe_chef_tip_recipe_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='benefits',
            field=models.TextField(blank=True, help_text='الفوائد الصحية للمشروب', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='item_type',
            field=models.CharField(choices=[('food', 'طعام'), ('drink', 'مشروب')], default='food', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'صغير'), ('medium', 'وسط'), ('large', 'كبير')], max_length=10, null=True),
        ),
    ]
