# Generated by Django 6.0.4 on 2026-04-26 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0013_add_drinks_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('weight_loss', 'خسارة الوزن'), ('muscle_gain', 'بناء العضلات'), ('cardio', 'كارديو واللياقة'), ('yoga', 'يوغا وتمدد'), ('crossfit', 'كروس فت'), ('rehabilitation', 'إعادة تأهيل'), ('nutrition_fitness', 'تغذية ولياقة'), ('general', 'لياقة عامة')], default='general', max_length=50)),
                ('experience_years', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='workout_videos/')),
                ('burned_calories', models.IntegerField(default=0, help_text='السعرات المحروقة المتوقعة')),
                ('duration', models.IntegerField(default=0, help_text='مدة التمرين بالدقائق')),
                ('difficulty', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'محترف')], default='beginner', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='nutrition.trainerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
