# Generated by Django 6.0.4 on 2026-04-26 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0014_userprofile_is_trainer_trainerprofile_workoutvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutvideo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutvideo',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='saved_workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkoutVideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_comments', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nutrition.workoutvideo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
