# Generated by Django 6.0.4 on 2026-05-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0015_workoutvideo_likes_workoutvideo_saves_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chefprofile",
            name="social_links",
            field=models.TextField(blank=True, null=True),
        ),
    ]
