# Generated by Django 6.0.4 on 2026-05-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0016_alter_chefprofile_social_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantprofile",
            name="social_links",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="restaurantprofile",
            name="location_url",
            field=models.TextField(blank=True),
        ),
    ]
