# Generated by Django 6.0.4 on 2026-05-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0017_restaurantprofile_social_links_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainerprofile",
            name="social_links",
            field=models.TextField(blank=True, null=True),
        ),
    ]
